version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/LittleLemon"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/C7M3L2Lab/myproject"
    schedule:
      interval: "weekly"